# Generated by Django 3.1.2 on 2020-10-14 15:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the person who contacted customer support.', max_length=255, verbose_name='氏名')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text="customer's phone number.", max_length=128, region=None, verbose_name='電話番号')),
                ('affiliation', models.CharField(blank=True, help_text="customer's affiliation (optional).", max_length=255, null=True, verbose_name='所属')),
            ],
            options={
                'verbose_name_plural': 'お客様の連絡先情報',
            },
        ),
        migrations.CreateModel(
            name='MatterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='It is an ID that can be assigned to a record so that it can be uniquely identified for each matter.', primary_key=True, serialize=False, verbose_name='matter_id')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Represents the time when the person receiving the call entered the data into the system, i.e., the approximate time the call was received.', verbose_name='対応日時')),
                ('responder', models.CharField(help_text='The person who received the call.', max_length=255, verbose_name='受信者')),
                ('memo', models.TextField(help_text='A column where you fill in everything you can remember for now.', verbose_name='メモ')),
                ('title', models.CharField(blank=True, help_text='If you had one keyword to tell your colleagues about this telephone, it would be ...', max_length=255, null=True, verbose_name='要件')),
                ('place', models.CharField(blank=True, help_text='Where does this matter take place?', max_length=1024, null=True, verbose_name='場所')),
                ('date', models.DateField(blank=True, help_text='When will this matter take place?', null=True, verbose_name='日付')),
                ('time', models.TimeField(blank=True, help_text='What time does this matter take place?', null=True, verbose_name='時刻')),
                ('call_back_by', models.DateTimeField(blank=True, help_text='When do we have to call back to customer by?', null=True, verbose_name='折り返し期限')),
                ('calling', models.ForeignKey(help_text='the person who contacted customer support.', on_delete=django.db.models.deletion.PROTECT, to='CustomerSupportAPI.callingmodel', verbose_name='発信者')),
            ],
            options={
                'verbose_name_plural': '問い合わせ',
            },
        ),
    ]
