# Generated by Django 3.1.2 on 2020-10-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupportAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mattermodel',
            options={'verbose_name_plural': 'お問い合わせ内容'},
        ),
    ]
