# Generated by Django 3.1.2 on 2020-10-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerSupportAPI', '0002_auto_20201014_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callingmodel',
            options={'ordering': ['name', 'phone_number'], 'verbose_name_plural': 'お客様の連絡先情報'},
        ),
        migrations.AlterModelOptions(
            name='mattermodel',
            options={'get_latest_by': ['-call_back_by', 'timestamp'], 'verbose_name_plural': 'お問い合わせ内容'},
        ),
    ]
